server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:pass123@localhost:8761/eureka
security:
  basic:
    enabled: true
  user:
    name: user
    password: pass123